name: contao-backend-customizer

services:
    appserver:
        type: php:8.2
        via: cli
    node:
        type: node:24
        via: cli

tooling:
    composer:
        service: appserver
        cmd: composer

    ecs:
        service: appserver
        cmd: composer ecs

    npm:
        service: node
        description: Run npm commands

    gulp:
        service: node
        description: Run gulp commands
