services:
    bwein.backend_customizer.stylesheet_generator:
        class: Bwein\BackendCustomizer\Service\StyleSheetGenerator
        arguments:
            - #set by extension
            - #set by extension
            - #set by extension
            - #set by extension
            - "%kernel.project_dir%"
            - "@filesystem"
