services:
    _defaults:
        autowire: true
        autoconfigure: true

    Bwein\BackendCustomizer\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection}'

    bwein.backend_customizer.stylesheet_generator:
        alias: Bwein\BackendCustomizer\Service\StyleSheetGenerator
        deprecated: 'The "%alias_id%" alias is deprecated. Do not use it anymore.'
