services:
    _defaults:
        autowire: true
        autoconfigure: true

    Bwein\BackendCustomizer\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection}'

    Bwein\BackendCustomizer\EventListener\BackendResponseListener:
        tags:
            - { name: kernel.event_listener, event: kernel.response }
